import {
  College,
  Room,
  Faculty,
  TimetableSlot,
  Campus360Location,
  FoodItem,
  Notice,
  Order,
  UserProfile,
  FoodCourtPayoutConfig,
  Department,
} from '@/types';

export const SEED_COLLEGES: College[] = [
  {
    id: 'col_jspm_tathawade',
    name: "JSPM's Tathawade Technical Campus",
    shortName: 'JSPM Tathawade',
    city: 'Pune',
    state: 'Maharashtra',
    code: 'JSPM',
    tagline: 'Excellence in Engineering and Technology',
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'col_coep_tech',
    name: 'COEP Technological University',
    shortName: 'COEP Tech',
    city: 'Pune',
    state: 'Maharashtra',
    code: 'COEP',
    tagline: 'Legacy of Innovation since 1854',
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'col_mit_wpu',
    name: 'MIT World Peace University',
    shortName: 'MIT-WPU',
    city: 'Pune',
    state: 'Maharashtra',
    code: 'MIT-WPU',
    tagline: 'Center for Holistic Value-Based Education',
    active: true,
    createdAt: new Date().toISOString(),
  },
];

export const SUPER_ADMIN_ACCOUNT: UserProfile = {
  uid: 'super_admin_omkumar',
  role: 'super_admin',
  collegeId: 'all',
  name: 'Omkumar Gajanan Ingalkar',
  username: 'omkumar_01',
  email: 'omkumaringalkar1234@gmail.com',
  passwordHash: 'okgi1234ADMIN',
  status: 'active',
  createdAt: '2025-01-01T00:00:00Z',
  designation: 'Chief Platform Administrator & Founder',
};

// Initial Seed Food Court Owner for JSPM
export const SEED_CANTEEN_OWNER: UserProfile = {
  uid: 'canteen_owner_suresh',
  role: 'food_court_staff',
  collegeId: 'col_jspm_tathawade',
  name: 'Suresh Patil',
  username: 'suresh_canteen',
  email: 'suresh.patil@jspm.edu',
  phone: '+91 98765 43210',
  passwordHash: 'canteen123',
  status: 'active',
  createdAt: '2025-01-01T00:00:00Z',
  designation: 'Central Food Court Owner & Licensee',
  assignedFoodCourtId: 'fc_jspm_main',
  permissions: ['canteen_manager'],
};

// Initial Seed Student for JSPM Tathawade
export const SEED_STUDENT: UserProfile = {
  uid: 'usr_student_omkumar',
  role: 'student',
  collegeId: 'col_jspm_tathawade',
  name: 'omkumar',
  email: 'rbt26it18@jspm.edu',
  username: 'rbt26it18',
  registrationId: 'RBT26IT18',
  studentId: 'RBT26IT18',
  rollNumber: '18',
  department: 'Information Technology',
  division: 'Div A',
  year: '3rd Year',
  passwordHash: 'okgi1234',
  status: 'active',
  createdAt: '2025-01-01T00:00:00Z',
};

// Initial Seed College Admin for JSPM Tathawade
export const SEED_COLLEGE_ADMIN: UserProfile = {
  uid: 'admin_sunita_yadav',
  role: 'college_admin',
  collegeId: 'col_jspm_tathawade',
  name: 'Sunita Yadav',
  email: 'admin@jspm.edu',
  username: 'sunita_admin',
  phone: '+91 98220 54321',
  passwordHash: 'admin123',
  designation: 'Campus Dean & Principal Administrator',
  status: 'active',
  createdAt: '2025-01-01T00:00:00Z',
};

// Initial Seed Faculty Member for JSPM Tathawade
export const SEED_FACULTY_USER: UserProfile = {
  uid: 'fac_sneha',
  role: 'teacher_staff',
  collegeId: 'col_jspm_tathawade',
  name: 'Prof. Sneha Deshmukh',
  email: 'sneha.deshmukh@jspm.edu',
  username: 'sneha_faculty',
  phone: '+91 98230 11223',
  department: 'Information Technology',
  designation: 'Assistant Professor & Class Teacher',
  isClassTeacher: true,
  assignedDivision: 'Div A',
  passwordHash: 'faculty123',
  status: 'active',
  createdAt: '2025-01-01T00:00:00Z',
};

export const DEMO_PROFILES: Record<string, UserProfile> = {
  // Super Admin
  'omkumaringalkar1234@gmail.com': SUPER_ADMIN_ACCOUNT,
  'omkumar_01': SUPER_ADMIN_ACCOUNT,
  'super_admin': SUPER_ADMIN_ACCOUNT,
  'superadmin': SUPER_ADMIN_ACCOUNT,

  // Student
  'rbt26it18@jspm.edu': SEED_STUDENT,
  'rbt26it18': SEED_STUDENT,
  'omkumar': SEED_STUDENT,
  'student@jspm.edu': SEED_STUDENT,
  'student': SEED_STUDENT,

  // College Admin
  'admin@jspm.edu': SEED_COLLEGE_ADMIN,
  'sunita_admin': SEED_COLLEGE_ADMIN,
  'college_admin': SEED_COLLEGE_ADMIN,
  'admin': SEED_COLLEGE_ADMIN,

  // Faculty / Staff
  'sneha.deshmukh@jspm.edu': SEED_FACULTY_USER,
  'sneha_faculty': SEED_FACULTY_USER,
  'teacher_staff': SEED_FACULTY_USER,
  'faculty': SEED_FACULTY_USER,
  'staff': SEED_FACULTY_USER,

  // Canteen Owner
  'suresh.patil@jspm.edu': SEED_CANTEEN_OWNER,
  'suresh_canteen': SEED_CANTEEN_OWNER,
  'food_court_staff': SEED_CANTEEN_OWNER,
  'canteen': SEED_CANTEEN_OWNER,
};

export const SEED_DEPARTMENTS: Department[] = [
  { id: 'dept_it', collegeId: 'col_jspm_tathawade', name: 'Information Technology', code: 'IT' },
  { id: 'dept_cs', collegeId: 'col_jspm_tathawade', name: 'Computer Science', code: 'CS' },
  { id: 'dept_mech', collegeId: 'col_jspm_tathawade', name: 'Mechanical Engineering', code: 'MECH' },
  { id: 'dept_entc', collegeId: 'col_jspm_tathawade', name: 'Electronics & Telecom', code: 'ENTC' },
  { id: 'dept_civil', collegeId: 'col_jspm_tathawade', name: 'Civil Engineering', code: 'CIVIL' },
  { id: 'dept_gen', collegeId: 'col_jspm_tathawade', name: 'General', code: 'GEN' },
];

export const SEED_ROOMS: Room[] = [
  {
    id: 'room_it_204',
    collegeId: 'col_jspm_tathawade',
    buildingId: 'bld_main',
    buildingName: 'Main Building',
    floor: '2nd Floor',
    roomNumber: 'IT-204',
    name: 'IT-204',
    type: 'Classroom',
    department: 'Information Technology',
    capacity: 70,
    description: 'Bright collaborative classroom near the east stairwell.',
    location360Id: 'loc_360_it204',
    departmentTeacher: 'Prof. Sneha Deshmukh',
    teacherPhone: '+91 98230 11223',
    teacherEmail: 'sneha.deshmukh@jspm.edu',
  },
  {
    id: 'room_dbms_lab',
    collegeId: 'col_jspm_tathawade',
    buildingId: 'bld_it',
    buildingName: 'IT Building',
    floor: '3rd Floor',
    roomNumber: 'IT-302',
    name: 'DBMS Lab',
    type: 'Lab',
    department: 'Information Technology',
    capacity: 45,
    description: 'High-performance database & systems lab with dual monitors and GPU clusters.',
    location360Id: 'loc_360_dbms',
    departmentTeacher: 'Prof. Sneha Deshmukh',
    teacherPhone: '+91 98230 11223',
    teacherEmail: 'sneha.deshmukh@jspm.edu',
  },
  {
    id: 'room_central_lib',
    collegeId: 'col_jspm_tathawade',
    buildingId: 'bld_main',
    buildingName: 'Main Building',
    floor: '1st Floor',
    roomNumber: 'LIB-101',
    name: 'Central Library',
    type: 'Library',
    department: 'General',
    capacity: 250,
    description: 'Quiet study zones, high-speed research terminals, and IEEE digital repository.',
    location360Id: 'loc_360_lib',
    departmentTeacher: 'Dr. Mohan Rao',
    teacherPhone: '+91 98222 33445',
    teacherEmail: 'mohan.rao@jspm.edu',
  },
  {
    id: 'room_auditorium',
    collegeId: 'col_jspm_tathawade',
    buildingId: 'bld_cultural',
    buildingName: 'Cultural Complex',
    floor: 'Ground Floor',
    roomNumber: 'AUD-01',
    name: 'Main Auditorium',
    type: 'Auditorium',
    department: 'Campus Wide',
    capacity: 850,
    description: 'Acoustically treated auditorium for keynote addresses, tech symposiums and convocations.',
    location360Id: 'loc_360_aud',
    departmentTeacher: 'Prof. Vikram Joshi',
    teacherPhone: '+91 98225 77889',
    teacherEmail: 'vikram.joshi@jspm.edu',
  },
  {
    id: 'room_canteen',
    collegeId: 'col_jspm_tathawade',
    buildingId: 'bld_amenities',
    buildingName: 'Campus Center',
    floor: 'Ground Floor',
    roomNumber: 'CC-01',
    name: 'Central Food Court',
    type: 'Canteen',
    department: 'Hospitality',
    capacity: 300,
    description: 'Spacious food court serving fresh hot snacks, meals, and beverages.',
    departmentTeacher: 'Suresh Patil',
    teacherPhone: '+91 98765 43210',
    teacherEmail: 'suresh.canteen@jspm.edu',
  },
  {
    id: 'room_ai_lab',
    collegeId: 'col_jspm_tathawade',
    buildingId: 'bld_it',
    buildingName: 'IT Building',
    floor: '3rd Floor',
    roomNumber: 'IT-305',
    name: 'Robotics & AI Lab',
    type: 'Lab',
    department: 'Information Technology',
    capacity: 40,
    description: 'Hardware prototyping kits, NVIDIA RTX workstations, and robotics arena.',
    location360Id: 'loc_360_ai',
    departmentTeacher: 'Dr. Rajesh Sharma',
    teacherPhone: '+91 98220 44556',
    teacherEmail: 'rajesh.sharma@jspm.edu',
  },
  {
    id: 'room_hod_it',
    collegeId: 'col_jspm_tathawade',
    buildingId: 'bld_main',
    buildingName: 'Main Building',
    floor: '2nd Floor',
    roomNumber: 'IT-201',
    name: 'HOD Office - IT',
    type: 'Office',
    department: 'Information Technology',
    capacity: 10,
    description: 'Departmental administration and student counseling office.',
    departmentTeacher: 'Dr. Rajesh Sharma',
    teacherPhone: '+91 98220 44556',
    teacherEmail: 'rajesh.sharma@jspm.edu',
  },
  // COEP Room to test isolation
  {
    id: 'room_coep_audi',
    collegeId: 'col_coep_tech',
    buildingId: 'bld_coep_heritage',
    buildingName: 'Heritage Main Building',
    floor: 'Ground Floor',
    roomNumber: 'COEP-101',
    name: 'Boat Club Hall',
    type: 'Auditorium',
    department: 'General',
    description: 'Historic assembly hall facing Mula river.',
    departmentTeacher: 'Dr. P. V. Kulkarni',
    teacherPhone: '+91 98221 12345',
    teacherEmail: 'pvk@coep.ac.in',
  },
];

export const SEED_FACULTY: Faculty[] = [
  {
    id: 'fac_sneha',
    collegeId: 'col_jspm_tathawade',
    name: 'Prof. Sneha Deshmukh',
    email: 'sneha.deshmukh@jspm.edu',
    phone: '+91 98230 11223',
    department: 'Information Technology',
    designation: 'Assistant Professor',
    subjects: ['Database Management Systems', 'Advanced Database Engineering'],
    officeRoom: 'IT-208',
    isClassTeacher: true,
    assignedDivision: 'Div A',
  },
  {
    id: 'fac_rajesh',
    collegeId: 'col_jspm_tathawade',
    name: 'Dr. Rajesh Sharma',
    email: 'rajesh.sharma@jspm.edu',
    phone: '+91 98220 44556',
    department: 'Information Technology',
    designation: 'HOD & Professor',
    subjects: ['Data Structures & Algorithms', 'System Design'],
    officeRoom: 'IT-201',
  },
  {
    id: 'fac_vikram',
    collegeId: 'col_jspm_tathawade',
    name: 'Prof. Vikram Joshi',
    email: 'vikram.joshi@jspm.edu',
    phone: '+91 98225 77889',
    department: 'Information Technology',
    designation: 'Associate Professor',
    subjects: ['Operating Systems', 'Cloud Computing & DevOps'],
    officeRoom: 'IT-210',
  },
  {
    id: 'fac_anjali',
    collegeId: 'col_jspm_tathawade',
    name: 'Prof. Anjali Patil',
    email: 'anjali.patil@jspm.edu',
    phone: '+91 98231 99001',
    department: 'Information Technology',
    designation: 'Assistant Professor',
    subjects: ['Computer Networks', 'Network Security'],
    officeRoom: 'IT-205',
  },
];

export const SEED_TIMETABLE: TimetableSlot[] = [
  // Monday (Day 1)
  {
    id: 'tt_mon_1',
    collegeId: 'col_jspm_tathawade',
    department: 'Information Technology',
    year: '3rd Year',
    division: 'Div A',
    dayOfWeek: 1,
    dayName: 'Monday',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    subject: 'Database Management Systems',
    subjectCode: 'IT301',
    room: 'IT-204',
    facultyName: 'Prof. Sneha Deshmukh',
    facultyId: 'fac_sneha',
    location360Id: 'loc_360_it204',
  },
  {
    id: 'tt_mon_2',
    collegeId: 'col_jspm_tathawade',
    department: 'Information Technology',
    year: '3rd Year',
    division: 'Div A',
    dayOfWeek: 1,
    dayName: 'Monday',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    subject: 'Computer Networks',
    subjectCode: 'IT302',
    room: 'IT-205',
    facultyName: 'Prof. Anjali Patil',
    facultyId: 'fac_anjali',
  },
  {
    id: 'tt_mon_3',
    collegeId: 'col_jspm_tathawade',
    department: 'Information Technology',
    year: '3rd Year',
    division: 'Div A',
    dayOfWeek: 1,
    dayName: 'Monday',
    startTime: '11:15 AM',
    endTime: '01:15 PM',
    subject: 'DBMS Lab (Batch A1)',
    subjectCode: 'IT301L',
    room: 'DBMS Lab',
    facultyName: 'Prof. Sneha Deshmukh',
    facultyId: 'fac_sneha',
    location360Id: 'loc_360_dbms',
  },
  {
    id: 'tt_mon_4',
    collegeId: 'col_jspm_tathawade',
    department: 'Information Technology',
    year: '3rd Year',
    division: 'Div A',
    dayOfWeek: 1,
    dayName: 'Monday',
    startTime: '02:00 PM',
    endTime: '03:00 PM',
    subject: 'Operating Systems',
    subjectCode: 'IT303',
    room: 'IT-204',
    facultyName: 'Prof. Vikram Joshi',
    facultyId: 'fac_vikram',
  },

  // Tuesday (Day 2)
  {
    id: 'tt_tue_1',
    collegeId: 'col_jspm_tathawade',
    department: 'Information Technology',
    year: '3rd Year',
    division: 'Div A',
    dayOfWeek: 2,
    dayName: 'Tuesday',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    subject: 'Operating Systems',
    subjectCode: 'IT303',
    room: 'IT-204',
    facultyName: 'Prof. Vikram Joshi',
    facultyId: 'fac_vikram',
  },
  {
    id: 'tt_tue_2',
    collegeId: 'col_jspm_tathawade',
    department: 'Information Technology',
    year: '3rd Year',
    division: 'Div A',
    dayOfWeek: 2,
    dayName: 'Tuesday',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    subject: 'Data Structures & Algorithms',
    subjectCode: 'IT304',
    room: 'IT-204',
    facultyName: 'Dr. Rajesh Sharma',
    facultyId: 'fac_rajesh',
  },

  // Wednesday (Day 3)
  {
    id: 'tt_wed_1',
    collegeId: 'col_jspm_tathawade',
    department: 'Information Technology',
    year: '3rd Year',
    division: 'Div A',
    dayOfWeek: 3,
    dayName: 'Wednesday',
    startTime: '09:00 AM',
    endTime: '11:00 AM',
    subject: 'Robotics & AI Workshop',
    subjectCode: 'IT305W',
    room: 'Robotics & AI Lab',
    facultyName: 'Prof. Sneha Deshmukh',
    facultyId: 'fac_sneha',
    location360Id: 'loc_360_ai',
  },
];

export const SEED_360_LOCATIONS: Campus360Location[] = [
  {
    id: 'loc_360_jspm_main',
    collegeId: 'col_jspm_tathawade',
    name: 'Explore JSPM in 360°',
    description: 'Immersive 360° Clear Pona spatial tour of JSPM Tathawade Campus, buildings, smart classrooms, and facilities.',
    category: 'Campus Tour',
    buildingId: 'bld_main',
    floor: 'All Floors',
    roomId: 'room_it_204',
    thumbnail: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=600&q=80',
    embedUrl: 'https://tours.clearpano.com/I4EFHxcx',
    externalUrl: 'https://tours.clearpano.com/I4EFHxcx',
    active: true,
    displayOrder: 0,
  },
  {
    id: 'loc_360_it204',
    collegeId: 'col_jspm_tathawade',
    name: 'Classroom IT-204',
    description: 'Immersive 360° perspective of IT-204 collaborative smart lecture room.',
    category: 'Classrooms',
    buildingId: 'bld_main',
    floor: '2nd Floor',
    roomId: 'room_it_204',
    thumbnail: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=600&q=80',
    embedUrl: 'https://tours.clearpano.com/I4EFHxcx',
    externalUrl: 'https://tours.clearpano.com/I4EFHxcx',
    active: true,
    displayOrder: 1,
  },
  {
    id: 'loc_360_dbms',
    collegeId: 'col_jspm_tathawade',
    name: 'DBMS & Cloud Lab',
    description: 'Virtual walkthrough of the primary database and cloud systems laboratory.',
    category: 'Labs',
    buildingId: 'bld_it',
    floor: '3rd Floor',
    roomId: 'room_dbms_lab',
    thumbnail: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=600&q=80',
    embedUrl: 'https://tours.clearpano.com/I4EFHxcx',
    externalUrl: 'https://tours.clearpano.com/I4EFHxcx',
    active: true,
    displayOrder: 2,
  },
  {
    id: 'loc_360_lib',
    collegeId: 'col_jspm_tathawade',
    name: 'Central Reading Hall',
    description: 'Panoramic view of the library mezzanine and silent study pods.',
    category: 'Library',
    buildingId: 'bld_main',
    floor: '1st Floor',
    roomId: 'room_central_lib',
    thumbnail: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=600&q=80',
    embedUrl: 'https://tours.clearpano.com/I4EFHxcx',
    externalUrl: 'https://tours.clearpano.com/I4EFHxcx',
    active: true,
    displayOrder: 3,
  },
  {
    id: 'loc_360_aud',
    collegeId: 'col_jspm_tathawade',
    name: 'Auditorium Main Stage',
    description: 'Front row view of the main college auditorium with 850 capacity.',
    category: 'Auditorium',
    buildingId: 'bld_cultural',
    floor: 'Ground Floor',
    roomId: 'room_auditorium',
    thumbnail: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=600&q=80',
    embedUrl: 'https://tours.clearpano.com/I4EFHxcx',
    externalUrl: 'https://tours.clearpano.com/I4EFHxcx',
    active: true,
    displayOrder: 4,
  },
];

export const SEED_FOOD_ITEMS: FoodItem[] = [
  {
    id: 'food_vada_pav',
    collegeId: 'col_jspm_tathawade',
    foodCourtId: 'fc_jspm_main',
    name: 'Vada Pav',
    category: 'Popular',
    description: 'Mumbai-style potato slider with spicy garlic chutney & fried green chilli.',
    price: 15,
    prepTimeMinutes: 10,
    imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=500&q=80',
    available: true,
    isVeg: true,
  },
  {
    id: 'food_masala_dosa',
    collegeId: 'col_jspm_tathawade',
    foodCourtId: 'fc_jspm_main',
    name: 'Masala Dosa',
    category: 'Meals',
    description: 'Crispy golden crepe with spiced potato filling, coconut chutney & hot sambar.',
    price: 45,
    prepTimeMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=500&q=80',
    available: true,
    isVeg: true,
  },
  {
    id: 'food_cold_coffee',
    collegeId: 'col_jspm_tathawade',
    foodCourtId: 'fc_jspm_main',
    name: 'Cold Coffee',
    category: 'Drinks',
    description: 'Rich espresso blended with chilled creamy milk and Hershey chocolate drizzle.',
    price: 30,
    prepTimeMinutes: 5,
    imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=500&q=80',
    available: true,
    isVeg: true,
  },
  {
    id: 'food_samosa_pav',
    collegeId: 'col_jspm_tathawade',
    foodCourtId: 'fc_jspm_main',
    name: 'Samosa Pav',
    category: 'Quick Bites',
    description: 'Flaky pastry filled with spiced potatoes, served inside buttered pav.',
    price: 20,
    prepTimeMinutes: 8,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80',
    available: true,
    isVeg: true,
  },
  {
    id: 'food_masala_chai',
    collegeId: 'col_jspm_tathawade',
    foodCourtId: 'fc_jspm_main',
    name: 'Masala Chai',
    category: 'Drinks',
    description: 'Freshly brewed aromatic tea infused with crushed ginger and cardamom.',
    price: 10,
    prepTimeMinutes: 5,
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=500&q=80',
    available: true,
    isVeg: true,
  },
  {
    id: 'food_veg_sandwich',
    collegeId: 'col_jspm_tathawade',
    foodCourtId: 'fc_jspm_main',
    name: 'Veg Grilled Sandwich',
    category: 'Quick Bites',
    description: 'Toasted multi-tier sandwich layered with cucumber, tomato, potato and spicy mint.',
    price: 40,
    prepTimeMinutes: 12,
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=500&q=80',
    available: true,
    isVeg: true,
  },
  {
    id: 'food_veg_thali',
    collegeId: 'col_jspm_tathawade',
    foodCourtId: 'fc_jspm_main',
    name: 'Deluxe Veg Thali',
    category: 'Meals',
    description: 'Complete meal with 2 seasonal vegetables, dal tadka, jeera rice, 3 rotis & dessert.',
    price: 80,
    prepTimeMinutes: 18,
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80',
    available: true,
    isVeg: true,
  },
];

export const SEED_NOTICES: Notice[] = [
  {
    id: 'not_1',
    collegeId: 'col_jspm_tathawade',
    title: 'Techfest 2026: Build something bold',
    category: 'Event',
    timeAgo: '2 days ago',
    date: '25 Sep 2026',
    summary: 'Annual inter-college hackathon and technical symposium with ₹1.5L prize pool.',
    content: 'Registration is now open for students of all departments. Categories include AI & Automation, Web3, Green Tech, and Mobile Solutions. Pitch directly to venture leads.',
    venue: 'Main Auditorium & IT Labs',
  },
  {
    id: 'not_2',
    collegeId: 'col_jspm_tathawade',
    title: 'Library stays open till 9 PM this week',
    category: 'Campus',
    timeAgo: 'Yesterday',
    date: '20 Sep 2026',
    summary: 'Extended reading room hours for mid-semester examinations.',
    content: 'In view of upcoming unit tests and project submissions, Central Library reading zones will remain operational till 9:00 PM with Wi-Fi and power outlets active.',
    venue: 'Central Library, 1st Floor',
  },
  {
    id: 'not_3',
    collegeId: 'col_jspm_tathawade',
    title: 'Mid-sem project expo registrations are live',
    category: 'Opportunity',
    timeAgo: '2h ago',
    date: '21 Sep 2026',
    summary: 'Submit your capstone abstracts before Friday 5 PM.',
    content: 'Teams of 3-4 students from 3rd & Final year must submit abstract synopses on the departmental portal. Mentors will be allocated by Monday.',
    venue: 'Department Seminar Halls',
  },
];

export const SEED_ACTIVE_ORDER: Order = {
  id: 'ord_cc_4949',
  orderNumber: '#CC4949',
  collegeId: 'col_jspm_tathawade',
  foodCourtId: 'fc_jspm_main',
  studentUid: 'usr_student_omkumar',
  studentName: 'omkumar',
  studentIdentifier: 'RBT26IT18 · Div A',
  items: [
    {
      itemId: 'food_vada_pav',
      name: 'Vada Pav',
      price: 15,
      quantity: 5,
      subtotal: 75,
    },
  ],
  subtotal: 75,
  tax: 0,
  total: 75,
  paymentMethod: 'CASH',
  paymentStatus: 'cash_pending',
  orderStatus: 'placed',
  pickupOtp: '4827',
  createdAt: '2026-09-21T08:50:00Z',
  updatedAt: '2026-09-21T08:50:00Z',
  statusHistory: [
    {
      status: 'placed',
      timestamp: '2026-09-21T08:50:00Z',
      note: 'Order placed by student with Cash at Pickup option',
    },
  ],
};

export const SEED_PAYOUT_CONFIGS: Record<string, FoodCourtPayoutConfig> = {
  fc_jspm_main: {
    foodCourtId: 'fc_jspm_main',
    collegeId: 'col_jspm_tathawade',
    businessName: 'JSPM Central Food Court',
    accountHolderName: 'Suresh B. Patil',
    bankName: 'HDFC Bank',
    accountNumber: '50100492819283',
    ifscCode: 'HDFC0001234',
    upiVpa: 'suresh.canteen@okhdfcbank',
    gatewayProvider: 'UPI_DIRECT',
    settlementSchedule: 'instant',
    verified: true,
    updatedAt: new Date().toISOString(),
  },
};
